Add note about last change

diff --git a/ansible/roles/docker/files/usr/sbin/docker_maid b/ansible/roles/docker/files/usr/sbin/docker_maid
--- a/ansible/roles/docker/files/usr/sbin/docker_maid
+++ b/ansible/roles/docker/files/usr/sbin/docker_maid
@@ -19,15 +19,18 @@ else
     log "No unused containers found, not cleaning."
 fi
 
+# We try to remove all images because there's no reliable way of telling 
+# used and unused images apart. Removing used images will fail anyway so 
+# it should be fine.
 IMAGES=$(docker images -q)
 if [ ! -z "$IMAGES" ]
 then
-    log "Cleaning unused docker images:"
+    log "Cleaning docker images:"
     for i in $IMAGES
     do
         log "    $i"
     done
-    docker rmi $IMAGES
+    docker rmi $IMAGES || true
 else
     log "No unused images found, not cleaning."
 fi
